version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3
      - image: node:latest
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: root

    working_directory: /home/ubuntu/cci-demo-rails
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install npm
      - run: npm install
      - run: bundle install
      - run: bundle exec rake db:create db:schema:load --trace
      - run: bundle exec rake db:migrate
      - run: bundle exec rake test
