version: 2
jobs:
  build:
    docker:
      - image: koheisg/twitty:latest

    working_directory: /app
    steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: bundle exec rake db:create db:schema:load --trace
      - run: bundle exec rake db:migrate
      - run: bundle exec rake test
