version: 2
jobs:
  build:
    docker:
      - image: guzart/rails-app:020407070021
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: root

    working_directory: /app
    steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: bundle exec rake db:create db:schema:load --trace
      - run: bundle exec rake db:migrate
      - run: bundle exec rake test
